---
title: "elvisual"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{elvisual}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(elvisual)
```

Les fiches de métadonnées ont été exportées dans un dossier.

```{r metadata_dir}
metadata_dir=here::here("data-raw/OHM_metadata") # à adapter bien sûr
print(metadata_dir)
```

# Récupération des données depuis les fichiers .xml

On récupère les informations qu'on formatte dans un tableau.

```{r general_metadata}
metadata=el_get_metadata(metadata_dir)
```


```{r categories}
categories=el_get_categories(metadata_dir)
```


# Statistiques de base


```{r metadata_summary}
metadata_summary=el_metadata_summary(metadata)
```


# Nuages de mots

```{r keywords}
table_keywords=el_table_keywords(metadata)
head(table_keywords)
```

```{r wordcloud, fig.width=8,fig.height=6}
table_keywords=el_table_keywords(metadata) %>% 
  dplyr::filter(freq>2)

el_wordcloud(table_keywords,
             keywords_to_remove=c("OHM VR","Rhône"),
             max_size=10)
```

```{r FREE_wordcloud, fig.width=8,fig.height=6}
table_keywords_FREE=el_table_keywords(metadata) %>%
  dplyr::filter(type=="FREE")

el_wordcloud(table_keywords_FREE,
             keywords_to_remove=c("OHM VR","Rhône"),
             max_size=15)
```


# Graphes de relations


```{r graph_personnes, fig.height=8, fig.width=8, warning=FALSE, message=FALSE}
graph_data=el_graph_data(metadata,nodetype="personne")
el_graph(graph_data, shorten_name=TRUE)
```


```{r graph_organisations, fig.height=8, fig.width=8, warning=FALSE, message=FALSE}
graph_data=el_graph_data(metadata,nodetype="organisation")
el_graph(graph_data, shorten_name=TRUE)
```


# Vue temporelle


```{r}
table_time=el_table_time(metadata)
```

```{r timeline,fig.width=6,fig.height=4, warning=FALSE, message=FALSE}
el_timeline(table_time)
```


```{r timehist, echo=FALSE,fig.width=6,fig.height=4, warning=FALSE, message=FALSE}
el_timehist(table_time)
```

```{r durationhist,fig.width=6,fig.height=4, warning=FALSE, message=FALSE}
el_durationhist(table_time)
```


# Carte


```{r map, warning=FALSE, message=FALSE}
map_data=el_map_data(metadata)
```


```{r plot_map, warning=FALSE, message=FALSE}
el_map(map_data, mode="plot")
```

```{r view_map, warning=FALSE, message=FALSE}
el_map(map_data, mode="plot")
```

